# Generated by Django 5.2.6 on 2025-09-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
